### ISSUE TITLE
Require giving errors

### ISSUE THREAD

**Issue by nuclearace** [plamoni/SiriProxy#12]
When I try to start the proxy server I'm given this error: 

Erikscomputer:SiriProxy eriklittle$ sudo ruby ./start.rb
internal:lib/rubygems/custom_require:29:in `require': no such file to load -- plugins/thermostat/siriThermostat (LoadError)
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from ./start.rb:2:in `<main>'

**Comment by Intecpsp** [comment]
Did you delete the siriThermostat.rb?

**Comment by nuclearace** [comment]
Nope, it's still in the same place.

**Comment by Intecpsp** [comment]
in start.rb try removing 

require 'plugins/thermostat/siriThermostat'

**Comment by nuclearace** [comment]
It then gives the same error for the next one it is supposed to load.

internal:lib/rubygems/custom_require:29:in `require': no such file to load -- plugins/testproxy/testproxy (LoadError)
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from ./start.rb:2:in `<main>'

**Comment by DouweM** [comment]
See issue #11.

**Comment by plamoni** [comment]
Okay, everyone. This error is coming from using Ruby 1.9. I'm looking for a workaround and will post it soon.

**Comment by jpipas** [comment]
Getting a similar error but with a little extra added on top:

```
start.rb:2: warning: variable $KCODE is no longer effective; ignored
<internal:lib/rubygems/custom_require>:29:in `require': no such file to load -- plugins/thermostat/siriThermostat (LoadError)
from <internal:lib/rubygems/custom_require>:29:in `require'
from start.rb:4:in `<main>'
```

Using `ruby 1.9.2p290 (2011-07-09 revision 32553) [i386-darwin9]`

**Comment by jpipas** [comment]
I think I've fixed this....  however, I'm soo totally new to git that I'm not sure how to "push" you my changes without pushing my ca and demoCA dir's etc.

I'm also running into this problem on the server when trying to process any "request":

```
[Info - iPhone] Object: FinishSpeech
[Info - iPhone] Object: SpeechPacket
[Info - iPhone] Object: SpeechPacket
[Info - iPhone] Object: SpeechPacket
[Info - iPhone] Object: SpeechPacket
[Info - iPhone] Object: FinishSpeech
Assertion failed: (e > 0), function SslContext_t, file ssl.cpp, line 162.
Abort trap
```

Any help on pushing these fixes too you would be good :)

**Comment by shack1108** [comment]
I still get this error:

sudo ruby ./start.rb
./start.rb:3: warning: variable $KCODE is no longer effective; ignored
/Users/Andrew/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': no such file to load -- uuidtools (LoadError)
    from /Users/Andrew/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /Users/Andrew/Misc/SiriProxy/siriObjectGenerator.rb:2:in `<top (required)>'
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from internal:lib/rubygems/custom_require:29:in `require'
    from /Users/Andrew/Misc/SiriProxy/plugins/testproxy/testproxy.rb:2:in`<top (required)>'
    from internal:lib/rubygems/custom_require:29:in `require'
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from ./start.rb:5:in `<main>'

I'm running Ruby 1.9.2, and I've re-installed uuidtools a couple of times.

**Comment by netpro2k** [comment]
Please give the code on the refactored branch a shot. We have reworked how everything is loaded, which might help with this issue. (Note the changes in the README as well)

https://github.com/plamoni/SiriProxy/tree/refactored

**Comment by cnaeger** [comment]
The refactored code worked great.  Thanks.

Using Ruby 1.9.3 on Lion.

Chad
